-- Run this in Supabase SQL Editor

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text not null,
  author_id text,
  date text not null,
  link_url text,
  file_url text,
  file_name text
);

create table if not exists public.guest_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id text not null,
  author_name text,
  date text not null,
  link_url text,
  file_url text,
  file_name text,
  comments jsonb not null default '[]'::jsonb
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  author_id text not null,
  author_name text not null,
  content text not null,
  date_time text not null
);

alter table public.posts
  drop constraint if exists posts_title_not_empty,
  drop constraint if exists posts_content_not_empty,
  drop constraint if exists posts_author_not_empty,
  drop constraint if exists posts_date_not_empty;

alter table public.posts
  add constraint posts_title_not_empty check (char_length(trim(title)) > 0),
  add constraint posts_content_not_empty check (char_length(trim(content)) > 0),
  add constraint posts_author_not_empty check (char_length(trim(author)) > 0),
  add constraint posts_date_not_empty check (char_length(trim(date)) > 0);

alter table public.guest_posts
  drop constraint if exists guest_posts_title_not_empty,
  drop constraint if exists guest_posts_content_not_empty,
  drop constraint if exists guest_posts_author_id_not_empty,
  drop constraint if exists guest_posts_date_not_empty;

alter table public.guest_posts
  add constraint guest_posts_title_not_empty check (char_length(trim(title)) > 0),
  add constraint guest_posts_content_not_empty check (char_length(trim(content)) > 0),
  add constraint guest_posts_author_id_not_empty check (char_length(trim(author_id)) > 0),
  add constraint guest_posts_date_not_empty check (char_length(trim(date)) > 0);

alter table public.post_comments
  drop constraint if exists post_comments_author_id_not_empty,
  drop constraint if exists post_comments_author_name_not_empty,
  drop constraint if exists post_comments_content_not_empty,
  drop constraint if exists post_comments_date_time_not_empty;

alter table public.post_comments
  add constraint post_comments_author_id_not_empty check (char_length(trim(author_id)) > 0),
  add constraint post_comments_author_name_not_empty check (char_length(trim(author_name)) > 0),
  add constraint post_comments_content_not_empty check (char_length(trim(content)) > 0),
  add constraint post_comments_date_time_not_empty check (char_length(trim(date_time)) > 0);
