-- Run this in Supabase SQL Editor to stabilize blog/guest board storage.
-- Owner blog posts stay in public.posts. Member-written posts move to public.guest_posts.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text not null,
  author_id text,
  category text not null default 'study',
  date text not null,
  link_url text,
  file_url text,
  file_name text
);

create table if not exists public.guest_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id text not null,
  author_name text,
  category text not null default 'study',
  date text not null,
  link_url text,
  file_url text,
  file_name text,
  comments jsonb not null default '[]'::jsonb
);

alter table public.posts
  add column if not exists category text not null default 'study',
  add column if not exists author_id text,
  add column if not exists link_url text,
  add column if not exists file_url text,
  add column if not exists file_name text,
  drop constraint if exists posts_category_valid;

alter table public.guest_posts
  add column if not exists category text not null default 'study',
  add column if not exists author_name text,
  add column if not exists link_url text,
  add column if not exists file_url text,
  add column if not exists file_name text,
  add column if not exists comments jsonb not null default '[]'::jsonb,
  drop constraint if exists guest_posts_category_valid;

update public.posts
set category = 'study'
where category is null
   or category not in ('study', 'daily', 'info', 'notice');

update public.guest_posts
set category = 'study'
where category is null
   or category not in ('study', 'daily', 'info');

insert into public.guest_posts (
  title,
  content,
  author_id,
  author_name,
  category,
  date,
  link_url,
  file_url,
  file_name,
  comments
)
select
  p.title,
  p.content,
  p.author_id,
  coalesce(m.name, p.author),
  case
    when p.category in ('daily', 'info') then p.category
    else 'study'
  end,
  p.date,
  p.link_url,
  p.file_url,
  p.file_name,
  '[]'::jsonb
from public.posts p
left join public.members m on m.id = p.author_id
where p.author_id is not null
  and exists (
    select 1
    from public.members existing_member
    where existing_member.id = p.author_id
  )
  and not exists (
    select 1
    from public.guest_posts gp
    where gp.author_id = p.author_id
      and gp.title = p.title
      and gp.content = p.content
      and gp.date = p.date
  );

delete from public.posts p
where p.author_id is not null
  and exists (
    select 1
    from public.members existing_member
    where existing_member.id = p.author_id
  );

alter table public.posts
  add constraint posts_category_valid check (category in ('study', 'daily', 'info', 'notice'));

alter table public.guest_posts
  add constraint guest_posts_category_valid check (category in ('study', 'daily', 'info'));
