-- Run this in Supabase SQL Editor

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text not null,
  author_id text,
  category text not null default 'study',
  date text not null,
  link_url text,
  file_url text,
  file_name text
);

create table if not exists public.guest_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id text not null,
  author_name text,
  category text not null default 'study',
  date text not null,
  link_url text,
  file_url text,
  file_name text,
  comments jsonb not null default '[]'::jsonb
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  author_id text not null,
  author_name text not null,
  content text not null,
  date_time text not null
);

alter table public.posts
  add column if not exists category text not null default 'study',
  drop constraint if exists posts_title_not_empty,
  drop constraint if exists posts_content_not_empty,
  drop constraint if exists posts_author_not_empty,
  drop constraint if exists posts_date_not_empty,
  drop constraint if exists posts_category_valid;

update public.posts
set category = 'study'
where category is null
   or category not in ('study', 'daily', 'info', 'notice');

alter table public.posts
  add constraint posts_title_not_empty check (char_length(trim(title)) > 0),
  add constraint posts_content_not_empty check (char_length(trim(content)) > 0),
  add constraint posts_author_not_empty check (char_length(trim(author)) > 0),
  add constraint posts_date_not_empty check (char_length(trim(date)) > 0),
  add constraint posts_category_valid check (category in ('study', 'daily', 'info', 'notice'));

alter table public.guest_posts
  add column if not exists category text not null default 'study',
  drop constraint if exists guest_posts_title_not_empty,
  drop constraint if exists guest_posts_content_not_empty,
  drop constraint if exists guest_posts_author_id_not_empty,
  drop constraint if exists guest_posts_date_not_empty,
  drop constraint if exists guest_posts_category_valid;

update public.guest_posts
set category = 'study'
where category is null
   or category not in ('study', 'daily', 'info');

alter table public.guest_posts
  add constraint guest_posts_title_not_empty check (char_length(trim(title)) > 0),
  add constraint guest_posts_content_not_empty check (char_length(trim(content)) > 0),
  add constraint guest_posts_author_id_not_empty check (char_length(trim(author_id)) > 0),
  add constraint guest_posts_date_not_empty check (char_length(trim(date)) > 0),
  add constraint guest_posts_category_valid check (category in ('study', 'daily', 'info'));

alter table public.post_comments
  drop constraint if exists post_comments_author_id_not_empty,
  drop constraint if exists post_comments_author_name_not_empty,
  drop constraint if exists post_comments_content_not_empty,
  drop constraint if exists post_comments_date_time_not_empty;

alter table public.post_comments
  add constraint post_comments_author_id_not_empty check (char_length(trim(author_id)) > 0),
  add constraint post_comments_author_name_not_empty check (char_length(trim(author_name)) > 0),
  add constraint post_comments_content_not_empty check (char_length(trim(content)) > 0),
  add constraint post_comments_date_time_not_empty check (char_length(trim(date_time)) > 0);

-- Durable attachment storage (files) in Supabase Storage
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do nothing;
